[server]
public_port = 8080          # Public HTTP port (receives tunneled traffic from Traefik)
tunnel_port = 8443          # gRPC port for client connections
private_key = "founMdhFUQM0bQuC9x0jDwgF1STNbYwbdD6CjnoBM5E="  # Server private key

# List of authorized clients
[[peers]]
public_key = "fQbK4MEYCbmAlqAdvVXaIIiCS3Uq8sNYb6TlxA1YF4s="  # Client public key
domain = "localhost"  # Domain for this client
