[server]
public_port = 8080          # porta HTTP pubblica (riceve traffico tunnelato da Traefik)
tunnel_port = 8443          # porta gRPC per connessioni client
private_key = "founMdhFUQM0bQuC9x0jDwgF1STNbYwbdD6CjnoBM5E="  # chiave privata del server

# Lista client autorizzati
[[peers]]
public_key = "fQbK4MEYCbmAlqAdvVXaIIiCS3Uq8sNYb6TlxA1YF4s="  # chiave pubblica del client
domain = "localhost"  # dominio per questo client
