# Traefik v3 - Static Configuration
api:
  dashboard: true
  insecure: true  # Dashboard su :8081/dashboard/

log:
  level: INFO

entryPoints:
  web:
    address: ":5000"  # Entrypoint 1: simulazione lato server (traffico tunnel)

  dashboard:
    address: ":4000"  # Entrypoint 2: client dashboard (frontend + /api)

  # traefik:
  #   address: ":8081"  # Dashboard e API Traefik

providers:
  docker:
    exposedByDefault: false
    network: shitty-tunnel-net

  file:
    filename: /etc/traefik/dynamic.yml
    watch: true
