[package]
name = "st-client"
version.workspace = true
edition.workspace = true

[dependencies]
st-domain = { workspace = true }
st-protocol = { workspace = true }
st-infra = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
reqwest = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
toml = { workspace = true }
